from django.urls import path
from . import views
from django.contrib.auth.views import *

urlpatterns = [

    path('', views.web, name='index_public'),

    path('auth/login/', LoginView.as_view(template_name='home/login.html'), name='login_user'),
    path('auth/logout/', LogoutView.as_view(), name='logout_user'),

    path('profile/', views.view_profile, name='profile'),
    path('profile/update/', views.edit_profile, name='edit_profile'),

    path('profile/password/update/', views.UserPasswordChangeView.as_view(), name='change_password'),
    # url(r'^profile/password/update/(?P<pk>\d+)/$', views.change_password, name='change_password_with_pk'),

    path('profile/password/reset/', PasswordResetView.as_view(template_name='home/reset_password.html'),
        name='password_reset'),
    path('profile/password/reset/done/', PasswordResetDoneView.as_view(template_name='home/reset_password_done.html'),
        name='password_reset_done'),
    re_path(r'^profile/password/reset/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', PasswordResetConfirmView.as_view(),
        {'template_name': 'accounts/reset_password_confirm.html',
         'post_reset_redirect': 'accounts:password_reset_complete'}, name='password_reset_confirm'),
    path('profile/password/reset/complete/', PasswordResetCompleteView.as_view(template_name='home/login.html'),
        {'template_name': 'accounts/reset_password_complete.html'}, name='password_reset_complete'),

    path('dashboard/', views.index, name='index'),
    path('theme/', views.theme, name='theme'),
    path('language/', views.language, name='language'),

    path('administrator/setting/index/', views.SettingsListView.as_view(), name='settings_list'),
    path('administrator/setting/add/', views.SettingsCreateView.as_view(), name='settings_create'),
    path('administrator/setting/update/<int:settings_pk>/', views.SettingsUpdateView.as_view(),
        name='settings_update'),

    path('administrator/school/index/', views.SchoolListView.as_view(), name='school_list'),
    path('administrator/school/add/', views.SchoolCreateView.as_view(), name='school_create'),
    path('administrator/school/update/<int:school_pk>/', views.SchoolUpdateView.as_view(), name='school_update'),
    path('administrator/school/<int:school_pk>/view/', views.school_view, name='school_view'),
    path('administrator/school/<int:school_pk>/delete/', views.school_delete, name='school_delete'),

    path('administrator/role/index/', views.RoleListView.as_view(), name='role_list'),
    path('administrator/role/add/', views.RoleCreateView.as_view(), name='role_create'),
    path('administrator/role/update/<int:role_pk>/', views.RoleUpdateView.as_view(), name='role_update'),
    path('administrator/role/<int:role_pk>/delete/', views.role_delete, name='role_delete'),

    path('administrator/payment/index/', views.PaymentSettingListView.as_view(), name='payment_setting_list'),
    path('administrator/payment/paypal/', views.PaypalCreateView.as_view(), name='payment_create'),
    path('administrator/payment/pesa/', views.PesaCreateView.as_view(), name='pesa_create'),
    path('administrator/payment/update/<int:payment_mtd_pk>/', views.PaymentUpdateView.as_view(),
        name='payment_update'),
    path('administrator/payment/view/<int:payment_mtd_pk>/', views.payment_view, name='payment_view'),
    path('administrator/payment/delete/<int:payment_mtd_pk>/', views.payment_delete, name='payment_delete'),

    path('administrator/emailsetting/index/', views.EmailSettingsListView.as_view(), name='emailsetting_list'),
    path('administrator/emailsetting/add/', views.EmailSettingsCreateView.as_view(), name='emailsetting_create'),
    path('administrator/emailsetting/update/<int:emailsetting_pk>/', views.EmailSettingsUpdateView.as_view(),
        name='emailsetting_update'),
    path('administrator/emailsetting/<int:emailsetting_pk>/view/', views.emailsetting_view,
        name='emailsetting_view'),
    path('administrator/emailsetting/<int:emailsetting_pk>/delete/', views.emailsetting_delete,
        name='emailsetting_delete'),

    path('school_settings/', views.SchoolSettingView.as_view(), name='school_setting'),

    path('administrator/user/index/', views.manage_user, name='manage_users'),

    path('activate/user/<int:user_pk>', views.user_activate, name='activate_user'),
    path('deactivate/user/<int:user_pk>', views.user_deactivate, name='deactivate_user'),

    path('administrator/usercredential/index/', views.manage_credential, name='manage_credential'),
    path('administrator/activitylog/index/', views.activity, name='activity'),
    path('administrator/backup/index/', views.backup, name='backup'),

    path('frontoffice/purpose/index/', views.PurposeListView.as_view(), name='purpose_list'),
    path('frontoffice/purpose/add/', views.PurposeCreateView.as_view(), name='purpose_create'),
    path('frontoffice/purpose/edit/<int:purpose_pk>/', views.PurposeUpdateView.as_view(), name='purpose_update'),
    path('frontoffice/purpose/<int:purpose_pk>/', views.purpose_delete, name='purpose_delete'),

    path('administrator/superadmin/index/', views.SuperuserListView.as_view(), name='superuser_list'),
    path('administrator/superadmin/add/', views.superuser_create, name='superuser_create'),
    path('administrator/superadmin/update/<int:superuser_pk>/', views.superuser_update, name='superuser_update'),
    path('administrator/superadmin/view/<int:superuser_pk>/', views.superuser_view, name='superuser_view'),
    path('administrator/superadmin/delete/<int:superuser_pk>/', views.superuser_delete, name='superuser_delete'),

    path('teacher/index/', views.TeacherListView.as_view(), name='teacher_list'),
    path('teacher/add/', views.teacher_create, name='teacher_create'),
    path('teacher/edit/<int:teacher_pk>/', views.teacher_update, name='teacher_update'),
    path('teacher/view/<int:teacher_pk>/', views.teacher_view, name='teacher_view'),
    path('teacher/delete/<int:teacher_pk>/', views.teacher_delete, name='teacher_delete'),

    path('administrator/feedback/index/', views.FeedbackListView.as_view(), name='feedback_list'),
    # url(r'^administrator/feedback/add/$', views.FeedbackCreateView.as_view(), name='feedback_create'),
    path('administrator/feedback/edit/<int:feedback_pk>/', views.FeedbackUpdateView.as_view(),
        name='feedback_update'),
    path('administrator/feedback/delete/<int:feedback_pk>/', views.feedback_delete, name='feedback_delete'),

    path('publish/feedback/<int:feedback_pk>', views.publish, name='publish_feedback'),
    path('unpublish/feedback/<int:feedback_pk>', views.unpublish, name='unpublish_feedback'),

    path('hrm/designation/index/', views.DesignationListView.as_view(), name='designation_list'),
    path('hrm/designation/add/', views.DesignationCreateView.as_view(), name='designation_create'),
    path('hrm/designation/edit/<int:designation_pk>/', views.DesignationUpdateView.as_view(),
        name='designation_update'),
    path('hrm/designation/delete/<int:designation_pk>/', views.designation_delete, name='designation_delete'),

    path('administrator/emailtemplate/index/', views.EmailtemplateListView.as_view(), name='emailtemplate_list'),
    path('administrator/emailtemplate/add/', views.EmailtemplateCreateView.as_view(), name='emailtemplate_create'),
    path('administrator/emailtemplate/edit/<int:emailtemplate_pk>/', views.EmailtemplateUpdateView.as_view(),
        name='emailtemplate_update'),
    path('administrator/emailtemplate/delete/<int:emailtemplate_pk>/', views.emailtemplate_delete,
        name='emailtemplate_delete'),

    path('administrator/smstemplate/index/', views.SmstemplateListView.as_view(), name='smstemplate_list'),
    path('administrator/smstemplate/add/', views.SmstemplateCreateView.as_view(), name='smstemplate_create'),
    path('administrator/smstemplate/edit/<int:smstemplate_pk>/', views.SmstemplateUpdateView.as_view(),
        name='smstemplate_update'),
    path('administrator/smstemplate/delete/<int:smstemplate_pk>/', views.smstemplate_delete,
        name='smstemplate_delete'),

    path('hrm/employee/index/', views.EmployeeListView.as_view(), name='employee_list'),
    path('hrm/employee/add/', views.employee_create, name='employee_create'),
    path('hrm/employee/edit/<int:employee_pk>/', views.employee_update, name='employee_update'),
    path('hrm/employee/view/<int:employee_pk>/', views.employee_view, name='employee_view'),
    path('hrm/employee/delete/<int:employee_pk>/', views.employee_delete, name='employee_delete'),

    path('student/type/index/', views.StudentTypeListView.as_view(), name='student_type_list'),
    path('student/type/add/', views.StudentTypeCreateView.as_view(), name='student_type_create'),
    path('student/type/edit/<int:student_type_pk>/', views.StudentTypeUpdateView.as_view(),
        name='student_type_update'),
    path('student/type/delete/<int:student_type_pk>/', views.student_type_delete, name='student_type_delete'),

    path('student/index/', views.StudentListView.as_view(), name='student_list'),
    path('student/admission/index/', views.OnlineStudentListView.as_view(), name='online_student_list'),
    path('student/add/', views.student_create, name='student_create'),
    path('student/edit/<int:student_pk>/', views.student_update, name='student_update'),
    path('student/view/<int:student_pk>/', views.student_view, name='student_view'),
    path('student/delete/<int:student_pk>/', views.student_delete, name='student_delete'),

    path('student/activity/index/', views.ActivityListView.as_view(), name='activity_list'),
    path('student/activity/add/', views.ActivityCreateView.as_view(), name='activity_create'),
    path('student/activity/edit/<int:activity_pk>/', views.ActivityUpdateView.as_view(), name='activity_update'),
    path('student/activity/view/<int:activity_pk>/', views.activity_view, name='activity_view'),
    path('student/activity/delete/<int:activity_pk>/', views.activity_delete, name='activity_delete'),

    path('card/admitsetting/index/', views.CardListView.as_view(), name='card_list'),
    path('card/admitsetting/add/', views.CardCreateView.as_view(), name='card_create'),
    path('card/admitsetting/edit/<int:card_pk>/', views.CardUpdateView.as_view(), name='card_update'),
    path('card/admitsetting/view/<int:card_pk>/', views.card_view, name='card_view'),
    path('card/admitsetting/delete/<int:card_pk>/', views.card_delete, name='card_delete'),

    path('card/idsetting/index/', views.AdmitListView.as_view(), name='admit_list'),
    path('card/idsetting/add/', views.AdmitCreateView.as_view(), name='admit_create'),
    path('card/idsetting/edit/<int:admit_pk>/', views.AdmitUpdateView.as_view(), name='admit_update'),
    path('card/idsetting/view/<int:admit_pk>/', views.admit_view, name='admit_view'),
    path('card/idsetting/delete/<int:admit_pk>/', views.admit_delete, name='admit_delete'),

    path('guardian/index/', views.guardian_list, name='guardian_list'),
    path('guardian/add/', views.guardian_create, name='guardian_create'),
    path('guardian/update/<int:guardian_pk>/', views.guardian_update, name='guardian_update'),
    path('guardian/view/<int:guardian_pk>/', views.guardian_view, name='guardian_view'),
    path('guardian/delete/<int:guardian_pk>/', views.guardian_delete, name='guardian_delete'),

    path('academic/classes/index/', views.ClassroomListView.as_view(), name='classroom_list'),
    path('academic/classes/add/', views.ClassroomCreateView.as_view(), name='classroom_create'),
    path('academic/classes/update/<int:classroom_pk>/', views.ClassroomUpdateView.as_view(),
        name='classroom_update'),
    path('academic/classes/delete/<int:classroom_pk>/', views.classroom_delete, name='classroom_delete'),

    path('academic/section/index/', views.SectionListView.as_view(), name='section_list'),
    path('academic/section/add/', views.SectionCreateView.as_view(), name='section_create'),
    path('academic/section/update/<int:section_pk>/', views.SectionUpdateView.as_view(), name='section_update'),
    path('academic/section/delete/<int:section_pk>/', views.section_delete, name='section_delete'),

    path('administrator/year/index/', views.AcademicYearListView.as_view(), name='year_list'),
    path('administrator/year/add/', views.year_create, name='year_create'),
    path('administrator/year/update/<int:year_pk>/', views.year_update, name='year_update'),
    path('administrator/year/delete/<int:year_pk>/', views.year_delete, name='year_delete'),

    path('administrator/term/index/', views.term_list, name="term_list"),
    path('administrator/term/add/', views.term_create, name="term_create"),
    path('administrator/term/update/<int:term_pk>/', views.term_update, name="term_update"),
    path('administrator/term/delete/<int:term_pk>/', views.term_delete, name="term_delete"),

    path('academic/syllabus/index/', views.SyllabusListView.as_view(), name='syllabus_list'),
    path('academic/syllabus/add/', views.syllabus_create, name='syllabus_create'),
    path('academic/syllabus/edit/<int:syllabus_pk>/', views.SyllabusUpdateView.as_view(), name='syllabus_update'),
    path('academic/syllabus/view/<int:syllabus_pk>/', views.syllabus_view, name='syllabus_view'),
    path('academic/syllabus/delete/<int:syllabus_pk>/', views.syllabus_delete, name='syllabus_delete'),

    path('frontoffice/receive/index/', views.ReceiveListView.as_view(), name='receive_list'),
    path('frontoffice/receive/add/', views.ReceiveCreateView.as_view(), name='receive_create'),
    path('frontoffice/receive/edit/<int:receive_pk>/', views.ReceiveUpdateView.as_view(), name='receive_update'),
    path('frontoffice/receive/view/<int:receive_pk>/', views.receive_view, name='receive_view'),
    path('frontoffice/receive/delete/<int:receive_pk>/', views.receive_delete, name='receive_delete'),

    path('frontoffice/dispatch/index/', views.DispatchListView.as_view(), name='dispatch_list'),
    path('frontoffice/dispatch/add/', views.DispatchCreateView.as_view(), name='dispatch_create'),
    path('frontoffice/dispatch/edit/<int:dispatch_pk>/', views.DispatchUpdateView.as_view(),
        name='dispatch_update'),
    path('frontoffice/dispatch/view/<int:dispatch_pk>/', views.dispatch_view, name='dispatch_view'),
    path('frontoffice/dispatch/delete/<int:dispatch_pk>/', views.dispatch_delete, name='dispatch_delete'),

    path('academic/subject/index/', views.SubjectListView.as_view(), name='subject_list'),
    path('academic/subject/add/', views.SubjectCreateView.as_view(), name='subject_create'),
    path('academic/subject/edit/<int:subject_pk>/', views.SubjectUpdateView.as_view(), name='subject_update'),
    path('academic/subject/view/<int:subject_pk>/', views.subject_view, name='subject_view'),
    path('academic/subject/delete/<int:subject_pk>/', views.subject_delete, name='subject_delete'),

    re_path(r'^academic/subject/register/', views.subject_registration, name='subject_register'),
    re_path(r'^academic/subject/drop/', views.subject_drop, name='subject_drop'),

    path('academic/material/index/', views.MaterialListView.as_view(), name='material_list'),
    path('academic/material/add/', views.material_create, name='material_create'),
    path('academic/material/edit/<int:material_pk>/', views.MaterialUpdateView.as_view(), name='material_update'),
    path('academic/material/view/<int:material_pk>/', views.material_view, name='material_view'),
    path('academic/material/delete/<int:material_pk>/', views.material_delete, name='material_delete'),

    path('academic/routine/index/', views.routine_list, name='routine_list'),
    path('academic/routine/add/', views.routine_create, name='routine_create'),
    path('academic/routine/update/<int:routine_pk>/', views.RoutineUpdateView.as_view(), name='routine_update'),
    path('academic/routine/delete/<int:routine_pk>/', views.routine_delete, name='routine_delete'),

    # path('schedule/', views.schedule_main, name='schedule_main'),
    # path('schedule/new/', views.create_edit_slot, name='create_slot'),
    # path('slot/<int:id>/edit/', views.create_edit_slot, name='edit_slot'),

    path('leave/type/index/', views.LeaveListView.as_view(), name='leave_list'),
    path('leave/type/add/', views.leave_create, name='leave_create'),
    path('leave/type/update/<int:leave_pk>/', views.LeaveUpdateView.as_view(), name='leave_update'),
    path('leave/type/delete/<int:leave_pk>/', views.leave_delete, name='leave_delete'),

    path('leave/application/index/', views.new_application_list, name='application_list'),
    path('leave/application/add/', views.application_create, name='application_create'),
    path('leave/waiting/index/', views.waiting_application_list, name='waiting_application_list'),
    path('leave/declined/index/', views.declined_application_list, name='declined_application_list'),
    path('leave/approved/add/', views.approved_application_list, name='approved_application_list'),
    path('leave/application/update/<int:application_pk>/', views.ApplicationUpdateView.as_view(),
        name='application_update'),
    path('leave/application/view/<int:application_pk>/', views.application_view, name='application_view'),
    path('leave/application/delete/<int:application_pk>/', views.application_delete, name='application_delete'),

    path('waiting/list/<int:application_pk>', views.application_waiting, name='application_waiting'),
    path('decline/list/<int:application_pk>', views.application_decline, name='application_decline'),
    path('approve/list/<int:application_pk>', views.application_approve, name='application_approve'),

    path('<int:school_id>/bulk_students/', views.bulk_student_list, name='bulk_student_list'),
    path('<int:school_id>/bulk_student/create/', views.bulk_student_create, name='bulk_student_create'),

    path('assignment/index/', views.AssignmentListView.as_view(), name='assignment_list'),
    path('assignment/add/', views.assignment_create, name='assignment_create'),
    path('assignment/edit/<int:assignment_pk>/', views.AssignmentUpdateView.as_view(), name='assignment_update'),
    path('assignment/view/<int:assignment_pk>/', views.assignment_view, name='assignment_view'),
    path('assignment/delete/<int:assignment_pk>/', views.assignment_delete, name='assignment_delete'),

    path('exam/mark/index/', views.manage_mark, name='manage_mark'),
    path('exam/mark/score/<int:mark_pk>/', views.submit_mark, name='submit_mark'),

    re_path(r'^academic/promotion/carry-over-list/', views.promote, name='promote'),
    # url(r'^academic/promotion/repeat-list/', views.repeat_list, name='repeat_list'),
    path('exam/resultcard/index/', views.view_result, name="view_results"),

    path('exam/grade/index/', views.ExamGradeListView.as_view(), name='exam_grade_list'),
    path('exam/grade/add/', views.ExamGradeCreateView.as_view(), name='exam_grade_create'),
    path('exam/grade/edit/<int:exam_grade_pk>/', views.ExamGradeUpdateView.as_view(), name='exam_grade_update'),
    path('exam/grade/delete/<int:exam_grade_pk>/', views.exam_grade_delete, name='exam_grade_delete'),

    path('exam/index/', views.ExamListView.as_view(), name='exam_list'),
    path('exam/add/', views.ExamCreateView.as_view(), name='exam_create'),
    path('exam/update/<int:exam_pk>/', views.ExamUpdateView.as_view(), name='exam_update'),
    path('exam/delete/<int:exam_pk>/', views.exam_delete, name='exam_delete'),

    path('exam/schedule/index/', views.ExamScheduleListView.as_view(), name='exam_schedule_list'),
    path('exam/schedule/add/', views.ExamScheduleCreateView.as_view(), name='exam_schedule_create'),
    path('exam/schedule/edit/<int:exam_schedule_pk>/', views.ExamScheduleUpdateView.as_view(),
        name='exam_schedule_update'),
    path('exam/schedule/delete/<int:exam_schedule_pk>/', views.exam_schedule_delete,
        name='exam_schedule_delete'),

    path('exam/suggestion/index/', views.ExamSuggestionListView.as_view(), name='exam_suggestion_list'),
    path('exam/suggestion/add/', views.ExamSuggestionCreateView.as_view(), name='exam_suggestion_create'),
    path('exam/suggestion/edit/<int:exam_suggestion_pk>/', views.ExamSuggestionUpdateView.as_view(),
        name='exam_suggestion_update'),
    path('exam/suggestion/delete/<int:exam_suggestion_pk>/', views.exam_suggestion_delete,
        name='exam_suggestion_delete'),

    path('certificate/type/index', views.CertificateListView.as_view(), name='certificate_list'),
    path('certificate/type/add/', views.CertificateCreateView.as_view(), name='certificate_create'),
    path('certificate/type/edit/<int:certificate_pk>/', views.CertificateUpdateView.as_view(),
        name='certificate_update'),
    path('certificate/type/view/<int:certificate_pk>/', views.certificate_view, name='certificate_view'),
    path('certificate/type/delete/<int:certificate_pk>/', views.certificate_delete, name='certificate_delete'),

    path('frontoffice/calllog/index/', views.LogListView.as_view(), name='log_list'),
    path('frontoffice/calllog/add/', views.LogCreateView.as_view(), name='log_create'),
    path('frontoffice/calllog/edit/<int:log_pk>/', views.LogUpdateView.as_view(), name='log_update'),
    path('frontoffice/calllog/view/<int:log_pk>/', views.log_view, name='log_view'),
    path('frontoffice/calllog/delete/<int:log_pk>/', views.log_delete, name='log_delete'),

    path('library/book/index/', views.BookListView.as_view(), name='book_list'),
    path('library/book/add/', views.BookCreateView.as_view(), name='book_create'),
    path('library/book/edit/<int:book_pk>/', views.BookUpdateView.as_view(), name='book_update'),
    path('library/book/view/<int:book_pk>/', views.book_view, name='book_view'),
    path('library/book/delete/<int:book_pk>/', views.book_delete, name='book_delete'),

    path('library/ebook/index/', views.EBookListView.as_view(), name='ebook_list'),
    path('library/ebook/add/', views.EBookCreateView.as_view(), name='ebook_create'),
    path('library/ebook/edit/<int:ebook_pk>/', views.EBookUpdateView.as_view(), name='ebook_update'),
    path('library/ebook/view/<int:ebook_pk>/', views.ebook_view, name='ebook_view'),
    path('library/ebook/delete/<int:ebook_pk>/', views.ebook_delete, name='ebook_delete'),

    path('library/member/index/', views.LibraryMemberListView.as_view(), name='library_member_list'),
    path('library/member/add/', views.LibraryMemberCreateView.as_view(), name='library_member_create'),
    path('library/member/edit/<int:library_member_pk>/', views.LibraryMemberUpdateView.as_view(),
        name='library_member_update'),
    path('library/member/delete/<int:library_member_pk>/', views.library_member_delete,
        name='library_member_delete'),

    path('library/issue/index/', views.IssueListView.as_view(), name='issue_list'),
    path('library/issue/add/', views.IssueCreateView.as_view(), name='issue_create'),
    path('library/issue/update/<int:issue_pk>/', views.IssueUpdateView.as_view(), name='issue_update'),
    path('library/issue/delete/<int:issue_pk>/', views.issue_delete, name='issue_delete'),

    path('transport/vehicle/index/', views.VehicleListView.as_view(), name='vehicle_list'),
    path('transport/vehicle/add/', views.VehicleCreateView.as_view(), name='vehicle_create'),
    path('transport/vehicle/edit/<int:vehicle_pk>/', views.VehicleUpdateView.as_view(), name='vehicle_update'),
    path('transport/vehicle/view/<int:vehicle_pk>/', views.vehicle_view, name='vehicle_view'),
    path('transport/vehicle/delete/<int:vehicle_pk>/', views.vehicle_delete, name='vehicle_delete'),

    path('transport/route/index/', views.RouteListView.as_view(), name='route_list'),
    path('transport/route/add/', views.RouteCreateView.as_view(), name='route_create'),
    path('transport/route/update/<int:route_pk>/', views.RouteUpdateView.as_view(), name='route_update'),
    path('transport/route/view/<int:route_pk>/', views.route_view, name='route_view'),
    path('transport/route/delete/<int:route_pk>/', views.route_delete, name='route_delete'),

    path('transport/member/index/', views.TransportMemberListView.as_view(), name='transport_member_list'),
    path('transport/member/add/', views.TransportMemberCreateView.as_view(), name='transport_member_create'),
    path('transport/member/update/<int:transport_member_pk>/', views.TransportMemberUpdateView.as_view(),
        name='transport_member_update'),
    path('transport/member/delete/<int:transport_member_pk>/', views.transport_member_delete,
        name='transport_member_delete'),

    path('hostel/index/', views.HostelListView.as_view(), name='hostel_list'),
    path('hostel/add/', views.HostelCreateView.as_view(), name='hostel_create'),
    path('hostel/edit/<int:hostel_pk>/', views.HostelUpdateView.as_view(), name='hostel_update'),
    path('hostel/view/<int:hostel_pk>/', views.hostel_view, name='hostel_view'),
    path('hostel/delete/<int:hostel_pk>/', views.hostel_delete, name='hostel_delete'),

    path('hostel/room/index', views.RoomListView.as_view(), name='room_list'),
    path('hostel/room/add/', views.RoomCreateView.as_view(), name='room_create'),
    path('hostel/room/update/<int:room_pk>/', views.RoomUpdateView.as_view(), name='room_update'),
    path('hostel/room/view/<int:room_pk>/', views.room_view, name='room_view'),
    path('hostel/room/delete/<int:room_pk>/', views.room_delete, name='room_delete'),

    path('hostel/member/index/', views.HostelMemberListView.as_view(), name='hostel_member_list'),
    path('hostel/member/add/', views.HostelMemberCreateView.as_view(), name='hostel_member_create'),
    path('hostel/member/edit/<int:member_pk>/', views.HostelMemberUpdateView.as_view(),
        name='hostel_member_update'),
    path('hostel/member/delete/<int:member_pk>/', views.hostel_member_delete, name='hostel_member_delete'),

    path('message/mail/index/', views.EmailListView.as_view(), name='email_list'),
    path('message/mail/add/', views.EmailCreateView.as_view(), name='email_create'),
    path('message/mail/view/<int:email_pk>/', views.email_view, name='email_view'),
    path('message/mail/delete/<int:email_pk>/', views.email_delete, name='email_delete'),

    path('message/text/index/', views.SMSListView.as_view(), name='sms_list'),
    path('message/text/add/', views.SMSCreateView.as_view(), name='sms_create'),
    path('message/text/view/<int:SMS_pk>/', views.sms_view, name='sms_view'),
    path('message/text/sms/delete/<int:SMS_pk>/', views.sms_delete, name='sms_delete'),

    # url(r'^/$', views.MessageListView.as_view(), name='message_inbox'),
    # url(r'^message/compose/$', views.MessageCreateView.as_view(), name='message_compose'),
    # url(r'^message/update/(?P<news_pk>\d+)/$', views.NewsUpdateView.as_view(), name='news_update'),
    # url(r'^message/view/(?P<news_pk>\d+)/$', views.news_view, name='news_view'),
    # url(r'^message/delete/(?P<news_pk>\d+)/$', views.news_delete, name='news_delete'),

    path('message/inbox/', views.MessagesListView.as_view(), name='messages_list'),
    path('send-message/', views.send_message, name='send_message'),
    path('receive-message/', views.receive_message, name='receive_message'),
    re_path(r'^(?P<username>[\w.@+-]+)/$', views.ConversationListView.as_view(), name='conversation_detail'),

    path('announcement/notice/index/', views.NoticeListView.as_view(), name='notice_list'),
    path('announcement/notice/add/', views.NoticeCreateView.as_view(), name='notice_create'),
    path('announcement/notice/edit/<int:notice_pk>/', views.NoticeUpdateView.as_view(), name='notice_update'),
    path('announcement/notice/view/<int:notice_pk>/', views.notice_view, name='notice_view'),
    path('announcement/notice/delete/<int:notice_pk>/', views.notice_delete, name='notice_delete'),

    path('announcement/news/index/', views.NewsListView.as_view(), name='news_list'),
    path('announcement/news/add/', views.NewsCreateView.as_view(), name='news_create'),
    path('announcement/news/update/<int:news_pk>/', views.NewsUpdateView.as_view(), name='news_update'),
    path('announcement/news/view/<int:news_pk>/', views.news_view, name='news_view'),
    path('announcement/news/delete/<int:news_pk>/', views.news_delete, name='news_delete'),

    path('complain/type/index/', views.TypeListView.as_view(), name='type_list'),
    path('complain/type/add/', views.TypeCreateView.as_view(), name='type_create'),
    path('complain/type/update/<int:type_pk>/', views.TypeUpdateView.as_view(), name='type_update'),
    path('complain/type/delete/<int:type_pk>/', views.type_delete, name='type_delete'),

    path('complain/index/', views.ComplainListView.as_view(), name='complain_list'),
    path('complain/add/', views.ComplainCreateView.as_view(), name='complain_create'),
    path('complain/update/<int:complain_pk>/', views.ComplainUpdateView.as_view(), name='complain_update'),
    path('complain/view/<int:complain_pk>/', views.complain_view, name='complain_view'),
    path('complain/delete/<int:complain_pk>/', views.complain_delete, name='complain_delete'),

    path('announcement/holiday/index/', views.HolidayListView.as_view(), name='holiday_list'),
    path('announcement/holiday/add/', views.HolidayCreateView.as_view(), name='holiday_create'),
    path('announcement/holiday/update/<int:holiday_pk>/', views.HolidayUpdateView.as_view(),
        name='holiday_update'),
    path('announcement/holiday/view/<int:holiday_pk>/', views.holiday_view, name='holiday_view'),
    path('announcement/holiday/delete/<int:holiday_pk>/', views.holiday_delete, name='holiday_delete'),

    path('event/index/', views.EventListView.as_view(), name='event_list'),
    path('event/add/', views.EventCreateView.as_view(), name='event_create'),
    path('event/edit/<int:event_pk>/', views.EventUpdateView.as_view(), name='event_update'),
    path('event/view/<int:event_pk>/', views.event_view, name='event_view'),
    path('event/delete<int:event_pk>/', views.event_delete, name='event_delete'),

    path('frontoffice/visitor/index/', views.VisitorListView.as_view(), name='visitor_list'),
    path('frontoffice/visitor/add/', views.VisitorCreateView.as_view(), name='visitor_create'),
    path('frontoffice/visitor/view/<int:visitor_pk>/', views.visitor_view, name='visitor_view'),
    path('frontoffice/visitor/edit/<int:visitor_pk>/', views.VisitorUpdateView.as_view(), name='visitor_update'),
    path('frontoffice/visitor/delete/<int:visitor_pk>/', views.visitor_delete, name='visitor_delete'),

    path('visitor/checkout/<int:visitor_pk>', views.check_out, name='check_out'),

    path('payroll/grade/index/', views.SalaryGradeListView.as_view(), name='salary_grade_list'),
    path('payroll/grade/add/', views.salary_grade_create, name='salary_grade_create'),
    path('payroll/grade/edit/<int:salary_pk>/', views.SalaryGradeUpdateView.as_view(), name='salary_grade_update'),
    path('payroll/grade/delete/<int:salary_pk>/', views.salary_grade_delete, name='salary_grade_delete'),
    path('payroll/grade/view/<int:salary_pk>/', views.salary_grade_view, name='salary_grade_view'),

    path('payroll/payment/index/', views.salary_payment, name='payment_list'),
    path('payroll/payment/add/<int:pk>/', views.new_payment, name='new_payment'),
    path('payroll/payment/<int:pk>/', views.pay_employee, name='pay_employee'),


    re_path(r'^payroll/Salary-Paid/index/List/', views.Payment_List, name='Payment_List'),
    re_path(r'^payroll/Salary-Paid/index/SalaryPaid/', views.EmployeeSalaryPaid, name='PayingSalary'),
    re_path(r'^payroll/Salary-Paid/index/SalaryPaidReport/', views.EmployeeMonthlySalaryReport, name='SalaryReport'),
    re_path(r'^payroll/history/index/', views.PaymentHistory, name='SalaryHistory'),
    path('payroll/payment/index', views.salary_payment, name='salary_payment'),

    path('accounting/discount/index/', views.DiscountListView.as_view(), name='discount_list'),
    path('accounting/discount/add/', views.DiscountCreateView.as_view(), name='discount_create'),
    path('accounting/discount/update/<int:discount_pk>/', views.DiscountUpdateView.as_view(),
        name='discount_update'),
    path('accounting/discount/delete/<int:discount_pk>/', views.discount_delete, name='discount_delete'),

    path('accounting/feetype/', views.FeeTypeListView.as_view(), name='fee_type_list'),
    path('accounting/feetype/add/', views.FeeTypeCreateView.as_view(), name='fee_type_create'),
    # path('accounting/feetype/add', views.create_fees_type, name='fee_type_create'),
    # path('accounting/index/fees-type/Add', views.create_fees_type, name='create-fees-type'),
    path('accounting/feetype/update/<int:fee_type_pk>/', views.FeeTypeUpdateView.as_view(),
        name='fee_type_update'),
    path('accounting/feetype/delete/<int:fee_type_pk>/', views.fee_type_delete, name='fee_type_delete'),

    path('accounting/duefeeemail/index/', views.DueEmailListView.as_view(), name='due_fee_email_list'),
    path('accounting/duefeeemail/create/', views.DueEmailCreateView.as_view(), name='due_fee_email_create'),
    path('accounting/duefeeemail/view/<int:due_fee_email_pk>/', views.due_fee_email_view,
        name='due_fee_email_view'),
    path('accounting/duefeeemail/delete/<int:due_fee_email_pk>/', views.due_fee_email_delete,
        name='due_fee_email_delete'),

    path('accounting/duefeeesms/index/', views.DueSmsListView.as_view(), name='due_fee_sms_list'),
    path('accounting/duefeeesms/create/', views.DueSmsCreateView.as_view(), name='due_fee_sms_create'),
    path('accounting/duefeeesms/update/<int:due_fee_sms_pk>/', views.due_fee_sms_view, name='due_fee_sms_view'),
    path('accounting/duefeeesms/delete/<int:due_fee_sms_pk>/', views.due_fee_sms_delete,
        name='due_fee_sms_delete'),

    path('accounting/invoice/due/', views.due_fee_list, name='due_fee_list'),
    path('accounting/invoice/payment/fees/<int:pk>/', views.paying_fees, name='paying_fees'),
    path('accounting/invoice/payment/student/unpaid/dues/', views.student_dues_paid, name='student_dues_paid'),
    path('accounting/invoice/payment/student/paid/dues/', views.dues_paid_list, name='dues_paid_list'),

    path('accounting/income/index/', views.IncomeListView.as_view(), name='income_list'),
    path('accounting/income/create/', views.IncomeCreateView.as_view(), name='income_create'),
    path('accounting/income/update/<int:income_pk>/', views.IncomeUpdateView.as_view(), name='income_update'),
    path('accounting/income/delete/<int:income_pk>/', views.income_delete, name='income_delete'),

    path('accounting/incomehead/index/', views.IncomeHeadListView.as_view(), name='income_head_list'),
    path('accounting/incomehead/create/', views.IncomeHeadCreateView.as_view(), name='income_head_create'),
    path('accounting/incomehead/update/<int:income_head_pk>/', views.IncomeHeadUpdateView.as_view(),
        name='income_head_update'),
    path('accounting/incomehead/delete/<int:income_head_pk>/', views.income_head_delete,
        name='income_head_delete'),

    path('accounting/expenditure/index/', views.ExpenditureListView.as_view(), name='expenditure_list'),
    path('accounting/expenditure/create/', views.ExpenditureCreateView.as_view(), name='expenditure_create'),
    path('accounting/expenditure/update/<int:expenditure_pk>/', views.ExpenditureUpdateView.as_view(),
        name='expenditure_update'),
    path('accounting/expenditure/delete/<int:expenditure_pk>/', views.expenditure_delete,
        name='expenditure_delete'),

    path('accounting/exphead/index/', views.ExpenditureHeadListView.as_view(), name='expenditure_head_list'),
    path('accounting/exphead/create/', views.ExpenditureHeadCreateView.as_view(),
        name='expenditure_head_create'),
    path('accounting/exphead/update/<int:expenditure_head_pk>/', views.ExpenditureHeadUpdateView.as_view(),
        name='expenditure_head_update'),
    path('accounting/exphead/delete/<int:expenditure_head_pk>/', views.expenditure_head_delete,
        name='expenditure_head_delete'),

    path('accounting/invoice/index/', views.InvoiceListView.as_view(), name='invoice_list'),
    path('accounting/invoice/add/', views.invoice_create, name='invoice_create'),
    path('accounting/invoice/update/<int:invoice_pk>/', views.InvoiceUpdateView.as_view(), name='invoice_update'),
    path('accounting/invoice/view/<int:invoice_pk>/', views.invoice_view, name='invoice_view'),
    path('accounting/invoice/delete/<int:invoice_pk>/', views.invoice_delete, name='invoice_delete'),

    path('gallery/index/', views.GalleryListView.as_view(), name='gallery_list'),
    path('gallery/add/', views.GalleryCreateView.as_view(), name='gallery_create'),
    path('gallery/update/<int:gallery_pk>/', views.GalleryUpdateView.as_view(), name='gallery_update'),
    path('gallery/delete/<int:gallery_pk>/', views.gallery_delete, name='gallery_delete'),

    path('gallery/image/index/', views.ImageListView.as_view(), name='image_list'),
    path('gallery/image/create/', views.ImageCreateView.as_view(), name='image_create'),
    path('gallery/image/update/<int:image_pk>/', views.ImageUpdateView.as_view(), name='image_update'),
    path('gallery/image/view/<int:image_pk>/', views.image_view, name='image_view'),
    path('gallery/image/delete/<int:image_pk>/', views.image_delete, name='image_delete'),

    path('frontend/slider/index/', views.SliderListView.as_view(), name='slider_list'),
    path('frontend/slider/add/', views.SliderCreateView.as_view(), name='slider_create'),
    path('frontend/slider/update/<int:slider_pk>/', views.SliderUpdateView.as_view(), name='slider_update'),
    path('frontend/slider/view/<int:slider_pk>/', views.slider_view, name='slider_view'),
    path('frontend/slider/delete/<int:slider_pk>/', views.slider_delete, name='slider_delete'),

    path('frontend/about/index/', views.AboutListView.as_view(), name='about_list'),
    path('frontend/about/add/', views.AboutCreateView.as_view(), name='about_create'),
    path('frontend/about/update/<int:about_pk>/', views.AboutUpdateView.as_view(), name='about_update'),
    path('frontend/about/view/<int:about_pk>/', views.about_view, name='about_view'),
    path('frontend/about/delete/<int:about_pk>/', views.about_delete, name='about_delete'),

    path('frontend/index/', views.PageListView.as_view(), name='page_list'),
    path('frontend/add/', views.PageCreateView.as_view(), name='page_create'),
    path('frontend/update/<int:page_pk>/', views.PageUpdateView.as_view(), name='page_update'),
    path('frontend/view/<int:page_pk>/', views.page_view, name='page_view'),
    path('frontend/delete/<int:page_pk>/', views.page_delete, name='page_delete'),

    path('attendance/index/', views.manage_attendance, name='manage_attendance'),
    path('attendance/classroom/<int:pk>/students/', views.mark_attendance, name='mark_attendance'),
    path('report/<int:pk>/attendance/', views.attendance_report, name='attendance_report'),
    path('report/<int:pk>/attendance/download/', views.export_to_csv, name='export_to_csv'),

    # url(r'^attendance/(?P<pk>[0-9]+)/students/$', views.attendance_student, name='attendance_student'),
    path('attendance/teachers/', views.attendance_teacher, name='attendance_teacher'),
    path('attendance/employees/', views.attendance_employee, name='attendance_employee'),

    path('exam/mark/index/', views.manage_mark, name='manage_mark'),
    path('exam/mark/score/<int:mark_pk>/', views.submit_mark, name='submit_mark'),

    re_path(r'^Reports/Income/index', views.income_report, name='income-report'),
    re_path(r'^Reports/Expenditure/index', views.expenditure_report, name='expenditure-report'),
    re_path(r'^Reports/Invoices/index', views.invoices_report, name='invoices-report'),

    path('classrooms/ajax/', views.classrooms_ajax, name='classrooms_ajax'),
    path('classrooms/choices/ajax/', views.classrooms_choices_ajax, name='classrooms_choices_ajax'),
    path('sections/ajax/', views.sections_ajax, name='sections_ajax'),
    path('sections/choices/ajax/', views.sections_choices_ajax, name='sections_choices_ajax'),

    path('ajax/load-payment_to/', views.load_payment_to, name='ajax_load_payment_to'),
    path('ajax/load-subjects/', views.load_subjects, name='ajax_load_subjects'),
    path('ajax/load-exams/', views.load_exams, name='ajax_load_exams'),
    path('ajax/load-classrooms/', views.load_classrooms, name='ajax_load_classrooms'),
    path('ajax/load-teachers/', views.load_teachers, name='ajax_load_teachers'),
    path('ajax/load-employees/', views.load_employees, name='ajax_load_employees'),
    path('ajax/load-sections/', views.load_sections, name='ajax_load_sections'),
    path('ajax/load-roles/', views.load_roles, name='ajax_load_roles'),
    path('ajax/load-users/', views.load_users, name='ajax_load_users'),
    path('ajax/load-payees/', views.load_payees, name='ajax_load_payees'),
    path('ajax/load-user/', views.load_user, name='ajax_load_user'),
    path('ajax/load-userz/', views.load_userz, name='ajax_load_userz'),
    path('ajax/load-students/', views.load_students, name='ajax_load_students'),
    path('ajax/load-fee_types/', views.load_fee_types, name='ajax_load_fee_types'),
    path('ajax/load_fee_amount/', views.load_fee_amount, name='ajax_load_fee_amount'),
    path('ajax/load-student_discount/', views.load_student_discount, name='ajax_load_student_discount'),

]
